<?php

namespace Vibby\Bundle\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

  /**
   * Get the query to find all events included in 2 dates.
   *
   * @return array Some event entities.
   */
  public function findByDatesQuery($date1, $date2, $unwantedIds = array()) {

    $em = $this->getEntityManager();
    if ($date1 > $date2) {
      $temp = $date2;
      $date2 = $date1;
      $date1 = $temp;
    }
    $dql = "select e.id, e.date_from, e.date_to
            from Vibby\Bundle\BookingBundle\Entity\Event e
            where
            not(
              (
                e.date_from > '" . $date1->format('Y-m-d') . "'
              and
                e.date_from > '" . $date2->format('Y-m-d') . "'
              ) or (
                e.date_to < '" . $date1->format('Y-m-d') . "'
              and
                e.date_to < '" . $date2->format('Y-m-d') . "'
              )
            ) and (
              e.is_validated = 1
            )";
//    echo $dql;
    if (count($unwantedIds)) {
      $dql .= "
            and (
              e.id NOT IN (" . implode(',', $unwantedIds) . ")
            )
            ";
    }

    return $em->createQuery($dql);
  }
  
  
  /**
   * Finds all events included in 2 dates.
   *
   * @return array Some event entities.
   */
  public function findByDates($date1, $date2, $unwantedIds = array()) {
    
    return $this->findByDatesQuery($date1, $date2, $unwantedIds)->getResult();
    
  }
  
  /**
   * Finds all events included in 2 dates.
   *
   * @return array Some event entities.
   */
  public function listAllQuery() {
    
    $dql = "select e
              from Vibby\Bundle\BookingBundle\Entity\Event e
            ";

    return $this->getEntityManager()->createQuery($dql);
    
  }

  public function getBookedIntervals($events) {
    
    $dates = array();
    $prevDateTo = 0;
    foreach ($events as $event) {
      if ($prevDateTo != $event["date_from"]->format('Ymd')) {
        $dates[] = array(
            $event["date_from"]->format('U') + 60 * 60 * 24 * .5,
            $event["date_to"]->format('U') + 60 * 60 * 24 * .5,
        );
      } else {
        $dates[count($dates) - 1][1] = $event["date_to"]->format('U');
      }
      $prevDateTo = $event["date_to"]->format('U');
    }

    return $dates;
  }

}